
UPDATE HeroSpotter.locations SET name = 'Karl Marx Industries, LLC1', address = '2304 Woodbourne Avenue, Apt 3, Louisville, KY 40205', place_id = null, latitude = 0.000000, longitude = 0.000000 WHERE id = 2;
UPDATE HeroSpotter.locations SET name = 'blah blah ', address = '1200 Story Avenue, Louisville, KY, USA', place_id = null, latitude = 0.000000, longitude = 0.000000 WHERE id = 6;
UPDATE HeroSpotter.locations SET name = 'blah', address = '1600 Pennsylvania Ave, Jeffersonville, IN, USA', place_id = null, latitude = 0.000000, longitude = 0.000000 WHERE id = 7;
UPDATE HeroSpotter.locations SET name = 'asdfa', address = 'ASDF, Charai, Borla, Union Park, Chembur, Mumbai, Maharashtra, India', place_id = '', latitude = 0.000000, longitude = 0.000000 WHERE id = 13;
UPDATE HeroSpotter.locations SET name = '[unnamed location no. 401063]', address = '2343 Strathmoor Boulevard, Louisville, KY, USA', place_id = 'ChIJv4db0FsLaYgRNlbO6fZZFZs', latitude = 0.000000, longitude = 0.000000 WHERE id = 18;
UPDATE HeroSpotter.locations SET name = '[unnamed location no. 351318]', address = '234 South Main Street, Ashley, OH, USA', place_id = '', latitude = 0.000000, longitude = 0.000000 WHERE id = 19;
UPDATE HeroSpotter.locations SET name = 'askdjflkajdslkfa', address = '1026 South 4th Street, Louisville, KY, USA', place_id = 'ChIJQ6-6dFMNaYgRUXpggiuFXKY', latitude = 38.237794, longitude = -85.760343 WHERE id = 21;
UPDATE HeroSpotter.locations SET name = '[unnamed location no. 568870]', address = 'Avenida Callao 1234, Buenos Aires, Argentina', place_id = 'ChIJg_IllL3KvJURavpO1lRgUPY', latitude = -34.594322, longitude = -58.393310 WHERE id = 22;
UPDATE HeroSpotter.locations SET name = '[expletive]ing place', address = '1341 South 3rd Street, Louisville, KY, USA', place_id = 'ChIJueshYFANaYgRiUK3oMCnScA', latitude = -33.428977, longitude = -70.621146 WHERE id = 23;
UPDATE HeroSpotter.locations SET name = 'Vapor', address = '227 E Breckinridge St, Louisville, KY 40203, USA', place_id = 'ChIJGVPfnrRyaYgR2YGlyjZl6BQ', latitude = 38.241424, longitude = -85.750654 WHERE id = 24;
UPDATE HeroSpotter.locations SET name = 'cape town', address = 'Cape Town, South Africa', place_id = 'ChIJ1-4miA9QzB0Rh6ooKPzhf2g', latitude = -33.924869, longitude = 18.424055 WHERE id = 25;
UPDATE HeroSpotter.locations SET name = 'old apt', address = 'No. 20, Qidong Street, Zhongzheng District, Taipei City, Taiwan', place_id = 'ChIJAyN0qHupQjQRtuPqC7sQsLs', latitude = 25.042542, longitude = 121.529149 WHERE id = 26;
UPDATE HeroSpotter.locations SET name = 'old apt', address = '23 Aylmer Street, Montreal, QC, Canada', place_id = 'EiVSdWUgQXlsbWVyLCBNb250csOpYWwsIFFDIEgyWCwgQ2FuYWRhIi4qLAoUChIJX54cDkgayUwRvk8ntFJ7JJYSFAoSCQ23ZBxUGslMEe_vHyE4MU5l', latitude = 45.507584, longitude = -73.575351 WHERE id = 27;
UPDATE HeroSpotter.locations SET name = 'blah', address = 'Juncal 2336, Buenos Aires, Argentina', place_id = 'ChIJoZ_eHZrKvJUR4yhM7n1qGPE', latitude = -34.591973, longitude = -58.400322 WHERE id = 28;
UPDATE HeroSpotter.locations SET name = 'Aniki Spa', address = 'No. 20, Ningxia Road, Datong District, Taipei City, Taiwan', place_id = 'ChIJGchoT2upQjQRtBlMvB5GUe8', latitude = 25.054933, longitude = 121.514857 WHERE id = 29;
UPDATE HeroSpotter.locations SET name = 'Current Apt', address = '2304 Woodbourne Avenue, Louisville, KY, USA', place_id = 'ChIJMzbsB6gMaYgRw6oFKLecX4g', latitude = 38.226971, longitude = -85.685005 WHERE id = 30;
UPDATE HeroSpotter.locations SET name = 'Brooklyn Apt', address = '206 East 104th Street, New York, NY, USA', place_id = 'EicyMDYgRSAxMDR0aCBTdCwgTmV3IFlvcmssIE5ZIDEwMDI5LCBVU0EiMRIvChQKEgnfsn2OAvbCiREYbXdOJH0dZxDOASoUChIJcx9gvwL2wokRpnYS9FR3Stw', latitude = 40.790131, longitude = -73.945310 WHERE id = 31;
UPDATE HeroSpotter.locations SET name = 'dhakjsdhfkj', address = '2323 Greenwood Avenue, Louisville, KY, USA', place_id = 'ChIJc79USTNtaYgRaF3_380JLWk', latitude = 38.241754, longitude = -85.793271 WHERE id = 32;
UPDATE HeroSpotter.locations SET name = 'The Software Guild', address = '200 South 5th Street, Louisville, KY, USA', place_id = 'ChIJf_VTiKRyaYgROQxDDkSLL_4', latitude = 38.255221, longitude = -85.758734 WHERE id = 33;
UPDATE HeroSpotter.organizations SET name = 'fourth international ', email = 'trotsky@gmail.com', url = '', phone_number = '+3311123156461', address = '95700 Roissy-en-France, France', description = 'The Fourth International (FI) is a revolutionary socialist international organisation consisting of followers of Leon Trotsky, or Trotskyists, with the declared goal of helping the working class overthrow capitalism and work toward international communism. The Fourth International was established in France in 1938 as Trotsky and his supporters, having been expelled from the Soviet Union, considered the Third International or Comintern to have become lost to Stalinism and incapable of leading the international working class to political power.', place_id = '', latitude = 0.000000, longitude = 0.000000 WHERE id = 1;
UPDATE HeroSpotter.organizations SET name = 'Karl Marx Industries, LLC1', email = '5042021062karlmarx@gmail.com', url = 'http://www.karlmarxindustries.com,', phone_number = 'unknown', address = '2304 Woodbourne Avenue, Apt 3, Louisville, KY 40205', description = 'Unicorn sed mustache dolore, meggings swag in small batch fixie cloud bread meditation aliqua bitters shoreditch tumeric. Ipsum magna dreamcatcher raw denim esse fugiat poutine vegan marfa gentrify quinoa retro. Dolore commodo kale chips, chicharrones ennui pug palo santo consectetur letterpress subway tile sunt hoodie. Food truck waistcoat freegan, neutra commodo in crucifix raw denim eu. Pabst blue bottle offal sint +1 cornhole pok pok. Chia PBR&B chicharrones selvage slow-carb, heirloom truffaut ut cred snackwave mixtape. Godard single-origin coffee kitsch tempor.', place_id = null, latitude = 0.000000, longitude = 0.000000 WHERE id = 2;
UPDATE HeroSpotter.organizations SET name = 'Karl Marx Industries, LLC2', email = '5042021062karlmarx@gmail.com', url = 'unknown', phone_number = '+23546432135', address = '200 West Broadway, Louisville, KY, USA', description = 'Taiyaki listicle flexitarian, ipsum butcher duis pinterest ut et nulla. Fam biodiesel slow-carb commodo tofu, neutra aute banjo nulla paleo wayfarers chillwave hammock gastropub. Jianbing iceland taxidermy, blue bottle bespoke cardigan pickled single-origin coffee selfies pop-up eu franzen 90''s retro organic. Ea tofu pour-over, schlitz quis brooklyn minim cardigan gastropub hashtag paleo scenester whatever. Enim in blue bottle, art party eu artisan skateboard four loko mollit.

', place_id = '', latitude = 0.000000, longitude = 0.000000 WHERE id = 3;
UPDATE HeroSpotter.organizations SET name = 'the mouseketeers', email = 'unknown', url = 'unknown', phone_number = 'unknown', address = 'unknown', description = 'Keffiyeh brunch try-hard, hell of sriracha ea tbh roof party dreamcatcher craft beer. Authentic raw denim salvia offal fingerstache ea lyft cupidatat pork belly enim ut meh kinfolk est coloring book. Mixtape heirloom offal bushwick dolore velit. Ut voluptate YOLO, cloud bread street art trust fund kale chips kickstarter aesthetic paleo. Pabst jean shorts echo park kogi palo santo, schlitz laborum selvage vegan. Lomo messenger bag pour-over man bun raclette, la croix anim art party blog mumblecore keytar direct trade irure godard tilde. Chambray YOLO unicorn fam, humblebrag hot chicken man braid pinterest prism organic pork belly irony flexitarian shaman.', place_id = null, latitude = 0.000000, longitude = 0.000000 WHERE id = 4;
UPDATE HeroSpotter.organizations SET name = 'Karl Marx Industries, LLC', email = '5042021062karlmarx@gmail.com', url = 'unknown', phone_number = '5028886195', address = '123 East Main Street, Louisville, KY, USA', description = 'Cold-pressed fixie elit, lo-fi cliche put a bird on it leggings. Ea chia esse blog meggings fingerstache kinfolk asymmetrical letterpress hoodie. Small batch lorem marfa elit. Ullamco 8-bit ugh, adaptogen schlitz mollit hammock wolf crucifix af ramps tilde fam ipsum intelligentsia. Snackwave tofu mixtape migas tilde vaporware, fanny pack freegan disrupt. Culpa reprehenderit cupidatat hot chicken echo park unicorn id, ut sed neutra pariatur single-origin coffee nulla.

', place_id = null, latitude = 0.000000, longitude = 0.000000 WHERE id = 5;
UPDATE HeroSpotter.organizations SET name = 'NOw different', email = 'unknown@gmail.com', url = 'none listed', phone_number = 'none listed', address = '123 East Main Street, Louisville, KY, USA', description = 'Intelligentsia laborum artisan banjo tofu godard. Trust fund eiusmod vegan cardigan shaman. Etsy master cleanse lo-fi messenger bag ramps, shabby chic actually gluten-free swag pabst kogi pork belly pitchfork. Labore quinoa magna, flannel man bun single-origin coffee readymade seitan fixie heirloom hammock tumeric poutine. Cray cloud bread keytar minim la croix intelligentsia nulla dreamcatcher retro asymmetrical banh mi wolf 8-bit live-edge id. IPhone voluptate try-hard vape cornhole, dolore duis magna heirloom. Occupy esse readymade pok pok occaecat chambray.', place_id = '', latitude = 0.000000, longitude = 0.000000 WHERE id = 6;
UPDATE HeroSpotter.organizations SET name = 'unicorns', email = 'unknown', url = 'unknown', phone_number = 'unknown', address = '23', description = 'Chia deep v minim flexitarian shaman gentrify narwhal consectetur excepteur authentic schlitz bespoke. Mumblecore austin pickled iPhone pabst swag offal. Health goth next level taxidermy viral four dollar toast pariatur yr irony aliqua lomo direct trade deserunt. Ullamco et in messenger bag trust fund est fixie taxidermy food truck pok pok veniam edison bulb sunt mumblecore. Hot chicken organic succulents la croix taxidermy pinterest truffaut minim heirloom. Aesthetic green juice eiusmod, qui freegan retro helvetica letterpress chia nulla. Mollit food truck ut green juice cold-pressed locavore try-hard dolore tattooed kale chips kogi mlkshk quis.

', place_id = null, latitude = 0.000000, longitude = 0.000000 WHERE id = 7;
UPDATE HeroSpotter.organizations SET name = 'radical fairies', email = 'unknown', url = 'unknown', phone_number = 'unknown', address = '123 East Main Street, Louisville, KY, USA', description = 'Hella gentrify plaid hell of vaporware vice portland magna, pitchfork fugiat typewriter ipsum. Ut ramps reprehenderit unicorn air plant. Subway tile 3 wolf moon man braid scenester keffiyeh, vice copper mug. Craft beer typewriter eu tote bag bicycle rights vegan polaroid neutra echo park. Literally man bun exercitation, meggings cold-pressed aliqua brooklyn veniam non tacos tote bag green juice photo booth id. Chicharrones vinyl meditation coloring book, in tumeric fixie waistcoat affogato. Lomo air plant forage deserunt, bicycle rights health goth occaecat.', place_id = null, latitude = 0.000000, longitude = 0.000000 WHERE id = 8;
UPDATE HeroSpotter.organizations SET name = 'blondes', email = 'asdf@gmail.com', url = 'unknown', phone_number = 'unknown', address = 'SDF Building, GP Block, Sector V, Bidhannagar, Kolkata, West Bengal, India', description = 'Venmo distillery laborum reprehenderit DIY jean shorts swag occaecat iceland farm-to-table retro. Austin ut laboris kale chips succulents letterpress. Hot chicken fashion axe magna vaporware minim elit tilde irony selvage mumblecore consectetur. VHS deep v sriracha duis fam vegan laboris wayfarers ut hella. Vice synth typewriter paleo master cleanse. Bespoke adipisicing synth, bitters slow-carb lyft yuccie cold-pressed truffaut subway tile art party four dollar toast cliche you probably haven''t heard of them fashion axe. Ipsum selvage sed franzen kombucha godard meggings meh cred church-key neutra cronut seitan.', place_id = null, latitude = 0.000000, longitude = 0.000000 WHERE id = 9;
UPDATE HeroSpotter.organizations SET name = 'brunettes', email = '5042021062karlmarx@gmail.com', url = 'unknown', phone_number = '5028886195', address = 'Werqanis, Kasımlı/Baykan/Siirt, Turkey', description = 'Tacos swag poke, non meditation cillum kale chips yr af seitan tofu blog hoodie man braid. Post-ironic craft beer put a bird on it bicycle rights proident, affogato air plant church-key ethical aute copper mug vegan. Pariatur labore flannel polaroid, fam vaporware yr DIY dolore veniam palo santo eiusmod. Aute knausgaard pug disrupt minim tacos la croix cliche venmo.', place_id = 'ChIJGXQ01k7rDEARHBgPsMVWq-c', latitude = 0.000000, longitude = 0.000000 WHERE id = 10;
UPDATE HeroSpotter.organizations SET name = 'sdfg', email = 'sdfg@asdkfl.com', url = 'none listed', phone_number = 'asdf', address = 'Jardim Santa Marina, Jacareí - State of São Paulo, 12312-340, Brazil', description = 'Slow-carb mollit copper mug offal asymmetrical laborum blue bottle bespoke. Tilde ex excepteur ugh. Man bun chicharrones viral literally whatever synth bicycle rights venmo cred. Green juice pabst vinyl sunt paleo. Messenger bag cupidatat et mumblecore. Raclette selvage freegan banh mi. Tacos fa[expletive]on axe four dollar toast hoodie crucifix mumblecore, consectetur pour-over.', place_id = 'ChIJ6f8esfXKzZQRmeHuoEMIS5A', latitude = 0.000000, longitude = 0.000000 WHERE id = 12;
UPDATE HeroSpotter.organizations SET name = 'shit', email = 'none listed', url = 'none listed', phone_number = 'none listed', address = '2234 Dundee Road, Louisville, KY, USA', description = 'fuck this piece of shit', place_id = 'ChIJCTNBlKQMaYgRNFSjEnGGQaQ', latitude = 0.000000, longitude = 0.000000 WHERE id = 13;
UPDATE HeroSpotter.organizations SET name = 'asdf [expletive] [expletive] [expletive]', email = 'unknown@none.org', url = 'http://www.4i.com', phone_number = '1', address = 'Calle de Albarracín, 33, Madrid, Spain', description = 'Put a bird on it vexillologist live-edge sint trust fund, blue bottle proident tumeric anim shabby chic. Aliquip lorem kitsch actually vaporware ea celiac pabst tattooed deserunt. Vape dreamcatcher pabst single-origin coffee VHS. Artisan affogato migas irure enamel pin gastropub excepteur brunch austin marfa lyft cupidatat. Waistcoat beard selvage subway tile roof party chillwave food truck. Letterpress air plant 90''s, reprehenderit celiac hexagon heirloom ut swag nisi four loko lyft next level.', place_id = 'ChIJeZdCZHIvQg0R4zSwsBC-Wbg', latitude = 40.432675, longitude = -3.631033 WHERE id = 16;
UPDATE HeroSpotter.organizations SET name = 'asdfasf', email = 'unknown@none.org', url = 'none listed', phone_number = '+1-212-555-1212', address = '13213 East Freeway, Houston, TX, USA', description = 'Lorem ipsum dolor amet distillery selfies glossier chia franzen, celiac esse sed pour-over non disrupt. Mlkshk narwhal poutine waistcoat, kale chips ethical cliche selvage cronut enim succulents mumblecore leggings. Food truck dreamcatcher farm-to-table mlkshk subway tile non nisi. Crucifix franzen pok pok, palo santo occaecat chambray wayfarers asymmetrical edison bulb yuccie disrupt in et. Migas craft beer kitsch, fingerstache umami food truck artisan consectetur consequat asymmetrical pour-over knausgaard duis.', place_id = 'ChIJJz53t3ujQIYR2QJEbfY1y54', latitude = 29.771951, longitude = -95.191658 WHERE id = 17;
UPDATE HeroSpotter.powers SET power_name = 'Trotskyism', description = 'Retro migas gochujang hashtag dreamcatcher banh m', is_unique = 0 WHERE id = 2;
UPDATE HeroSpotter.powers SET power_name = 'Great Leap Forward', description = 'Kale chips asymmetrical next level, mlkshk pok pok tumeric swag cred chambray marfa meditation mumblecore dreamcatcher banjo.', is_unique = 1 WHERE id = 9;
UPDATE HeroSpotter.powers SET power_name = 'Cultural Revolution', description = 'VHS mumblecore. Cardigan listicle trust fund, you probably haven''t heard of them lumber[expletive]ual vegan paleo edison bulb migas banh mi distillery jean shorts chillwave humblebrag', is_unique = 0 WHERE id = 10;
UPDATE HeroSpotter.powers SET power_name = 'Proletarian Internationalism', description = 'Shabby chic pop-up iPhone scenester freegan edison bulb tacos mixtape chia viral ethical cold-pressed activated charcoal. ', is_unique = 0 WHERE id = 11;
UPDATE HeroSpotter.powers SET power_name = 'Monkey Handling', description = 'Actually helvetica tilde, taxidermy sriracha etsy church-key blog enamel pin freegan succulents disrupt small batch hot chicken tacos. ', is_unique = 0 WHERE id = 12;
UPDATE HeroSpotter.sightings SET location_id = 6, super_id = 2, date = '2011-08-19', image_file = null, image_approved = 0, reporter_name = null WHERE id = 5;
UPDATE HeroSpotter.sightings SET location_id = 7, super_id = 3, date = '2011-08-19', image_file = null, image_approved = 0, reporter_name = null WHERE id = 6;
UPDATE HeroSpotter.sightings SET location_id = 21, super_id = 2, date = '2011-08-19', image_file = null, image_approved = 0, reporter_name = '' WHERE id = 10;
UPDATE HeroSpotter.sightings SET location_id = 7, super_id = 3, date = '2011-08-19', image_file = null, image_approved = 0, reporter_name = '[expletive]face' WHERE id = 11;
UPDATE HeroSpotter.sightings SET location_id = 13, super_id = 2, date = '2019-10-26', image_file = null, image_approved = 0, reporter_name = '[expletive] everyhing' WHERE id = 12;
UPDATE HeroSpotter.sightings SET location_id = 31, super_id = 2, date = '2019-10-26', image_file = null, image_approved = 0, reporter_name = 'karl marx' WHERE id = 13;
UPDATE HeroSpotter.supers SET name = 'fsdf', is_villain = 1, description = 'Four loko slow-carb 90''s, four dollar toast green juice la croix vaporware. Listicle 3 wolf moon butcher, kale chips meggings copper mug offal. Lyft iPhone fingerstache banjo. Brooklyn health goth pitchfork, sustainable DIY cloud bread poke tote bag church-key messenger bag. ' WHERE id = 1;
UPDATE HeroSpotter.supers SET name = 'Leon Trotsky', is_villain = 0, description = 'YOLO vaporware keytar tofu, knausgaard stumptown roof party vexillologist cray ennui affogato. Before they sold out shabby chic swag vegan hexagon subway tile gochujang irony mlkshk butcher narwhal you probably haven''t heard of them 90''s gentrify vaporware. Shaman trust fund direct trade pinterest. ' WHERE id = 2;
UPDATE HeroSpotter.supers SET name = 'Mao ZeDong', is_villain = 0, description = 'Banh mi pinterest art party [expletive] of succulents. Lomo readymade knausgaard air plant prism swag deep v fingerstache. Fixie semiotics normcore venmo yuccie meditation dreamcatcher. ' WHERE id = 3;
UPDATE HeroSpotter.supers SET name = 'test', is_villain = 0, description = 'asdfasdfkajsdfl;kadfs' WHERE id = 4;
UPDATE HeroSpotter.supers SET name = 'gs', is_villain = 0, description = 'segf' WHERE id = 5;
UPDATE HeroSpotter.supers SET name = 'asdflk', is_villain = 0, description = 'If you want to execute a Statement object many times, it will normally reduce execution time to use a PreparedStatement object instead. The main feature of a PreparedStatement object is that, unlike a Statement object, it is given an SQL statement when it is created. PROTECTS AGAINST SQL INJECTION ATTACKS' WHERE id = 6;
UPDATE HeroSpotter.supers SET name = 'mother[expletive]er', is_villain = 0, description = 'askdlflakjsdf [expletive] this [expletive]t' WHERE id = 8;
UPDATE HeroSpotter.supers SET name = '[expletive] this', is_villain = 1, description = 'Sustainable tote bag cillum single-origin coffee pabst fam, aesthetic affogato pour-over synth mlkshk farm-to-table. Next level keffiyeh migas, kombucha VHS pitchfork organic et duis tilde try-hard anim semiotics YOLO artisan. Kale chips literally meggings adaptogen jean shorts officia wolf roof party you probably haven''t heard of them blog nisi copper mug. Vexillologist dolor mixtape eu cred, exercitation actually cold-pressed pabst forage everyday carry subway tile single-origin coffee esse. Gentrify microdosing actually squid copper mug williamsburg tbh. Selvage ut direct trade marfa occaecat, hell of bitters plaid whatever.' WHERE id = 9;
